INSERT INTO `countries_capitals` (`capital`) VALUES ("Kabul");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tirana");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Algiers");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Andorra la Vella");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Luanda");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Saint John's");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Buenos Aires");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Yerevan");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Canberra");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vienna");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Baku");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Nassau");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Manama");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dhaka");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bridgetown");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Minsk");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Brussels");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Belmopan");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Porto-Novo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Thimphu");
INSERT INTO `countries_capitals` (`capital`) VALUES ("La Paz (administrative); Sucre (judicial)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Sarajevo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Gaborone");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Brasilia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bandar Seri Begawan");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Sofia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ouagadougou");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Gitega (changed from Bujumbura in December 2018)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Phnom Penh");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Yaounde");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ottawa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Praia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bangui");
INSERT INTO `countries_capitals` (`capital`) VALUES ("N'Djamena");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Santiago");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Beijing");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bogota");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Moroni");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Brazzaville");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kinshasa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("San Jose");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Yamoussoukro (official); Abidjan (de facto)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Zagreb");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Havana");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Nicosia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Prague");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Copenhagen");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Djibouti");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Roseau");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Santo Domingo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dili");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Quito");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Cairo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("San Salvador");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Malabo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Asmara");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tallinn");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Addis Ababa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Suva");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Helsinki");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Paris");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Libreville");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Banjul");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tbilisi");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Berlin");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Accra");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Athens");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Saint George's");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Guatemala City");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Conakry");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bissau");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Georgetown");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Port-au-Prince");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tegucigalpa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Budapest");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Reykjavik");
INSERT INTO `countries_capitals` (`capital`) VALUES ("New Delhi");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Jakarta");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tehran");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Baghdad");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dublin");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Jerusalem*");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Rome");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kingston");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tokyo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Amman");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Astana");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Nairobi");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tarawa Atoll");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Pyongyang");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Seoul");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Pristina");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kuwait City");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bishkek");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vientiane");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Riga");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Beirut");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Maseru");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Monrovia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tripoli");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vaduz");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vilnius");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Luxembourg");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Skopje");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Antananarivo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Lilongwe");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kuala Lumpur");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Male");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bamako");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Valletta");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Majuro");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Nouakchott");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Port Louis");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Mexico City");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Palikir");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Chisinau");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Monaco");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ulaanbaatar");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Podgorica");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Rabat");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Maputo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Rangoon (Yangon); Naypyidaw or Nay Pyi Taw (administrative)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Windhoek");
INSERT INTO `countries_capitals` (`capital`) VALUES ("no official capital; government offices in Yaren District");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kathmandu");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Amsterdam; The Hague (seat of government)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Wellington");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Managua");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Niamey");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Abuja");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Oslo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Muscat");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Islamabad");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Melekeok");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Panama City");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Port Moresby");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Asuncion");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Lima");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Manila");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Warsaw");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Lisbon");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Doha");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bucharest");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Moscow");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kigali");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Basseterre");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Castries");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kingstown");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Apia");
INSERT INTO `countries_capitals` (`capital`) VALUES ("San Marino");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Sao Tome");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Riyadh");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dakar");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Belgrade");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Victoria");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Freetown");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Singapore");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bratislava");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ljubljana");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Honiara");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Mogadishu");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Pretoria (administrative); Cape Town (legislative); Bloemfontein (judiciary)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Juba ");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Madrid");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Colombo; Sri Jayewardenepura Kotte (legislative)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Khartoum");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Paramaribo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Mbabane");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Stockholm");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bern");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Damascus");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Taipei");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dushanbe");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Dar es Salaam; Dodoma (legislative)");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Bangkok");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Lome");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Nuku'alofa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Port-of-Spain");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tunis");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ankara");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Ashgabat");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vaiaku village, Funafuti province");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kampala");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Kyiv");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Abu Dhabi");
INSERT INTO `countries_capitals` (`capital`) VALUES ("London");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Washington, D.C.");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Montevideo");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Tashkent");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Port-Vila");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Vatican City");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Caracas");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Hanoi");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Sanaa");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Lusaka");
INSERT INTO `countries_capitals` (`capital`) VALUES ("Harare");