INSERT INTO `countries_capitals` (`country`) VALUES ("Afghanistan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Albania");
INSERT INTO `countries_capitals` (`country`) VALUES ("Algeria");
INSERT INTO `countries_capitals` (`country`) VALUES ("Andorra");
INSERT INTO `countries_capitals` (`country`) VALUES ("Angola");
INSERT INTO `countries_capitals` (`country`) VALUES ("Antigua and Barbuda");
INSERT INTO `countries_capitals` (`country`) VALUES ("Argentina");
INSERT INTO `countries_capitals` (`country`) VALUES ("Armenia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Australia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Austria");
INSERT INTO `countries_capitals` (`country`) VALUES ("Azerbaijan");
INSERT INTO `countries_capitals` (`country`) VALUES ("The Bahamas");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bahrain");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bangladesh");
INSERT INTO `countries_capitals` (`country`) VALUES ("Barbados");
INSERT INTO `countries_capitals` (`country`) VALUES ("Belarus");
INSERT INTO `countries_capitals` (`country`) VALUES ("Belgium");
INSERT INTO `countries_capitals` (`country`) VALUES ("Belize");
INSERT INTO `countries_capitals` (`country`) VALUES ("Benin");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bhutan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bolivia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bosnia and Herzegovina");
INSERT INTO `countries_capitals` (`country`) VALUES ("Botswana");
INSERT INTO `countries_capitals` (`country`) VALUES ("Brazil");
INSERT INTO `countries_capitals` (`country`) VALUES ("Brunei");
INSERT INTO `countries_capitals` (`country`) VALUES ("Bulgaria");
INSERT INTO `countries_capitals` (`country`) VALUES ("Burkina Faso");
INSERT INTO `countries_capitals` (`country`) VALUES ("Burundi");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cambodia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cameroon");
INSERT INTO `countries_capitals` (`country`) VALUES ("Canada");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cape Verde");
INSERT INTO `countries_capitals` (`country`) VALUES ("Central African Republic");
INSERT INTO `countries_capitals` (`country`) VALUES ("Chad");
INSERT INTO `countries_capitals` (`country`) VALUES ("Chile");
INSERT INTO `countries_capitals` (`country`) VALUES ("China");
INSERT INTO `countries_capitals` (`country`) VALUES ("Colombia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Comoros");
INSERT INTO `countries_capitals` (`country`) VALUES ("Congo, Republic of the");
INSERT INTO `countries_capitals` (`country`) VALUES ("Congo, Democratic Republic of the");
INSERT INTO `countries_capitals` (`country`) VALUES ("Costa Rica");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cote d'Ivoire");
INSERT INTO `countries_capitals` (`country`) VALUES ("Croatia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cuba");
INSERT INTO `countries_capitals` (`country`) VALUES ("Cyprus");
INSERT INTO `countries_capitals` (`country`) VALUES ("Czech Republic");
INSERT INTO `countries_capitals` (`country`) VALUES ("Denmark");
INSERT INTO `countries_capitals` (`country`) VALUES ("Djibouti");
INSERT INTO `countries_capitals` (`country`) VALUES ("Dominica");
INSERT INTO `countries_capitals` (`country`) VALUES ("Dominican Republic");
INSERT INTO `countries_capitals` (`country`) VALUES ("East Timor (Timor-Leste)");
INSERT INTO `countries_capitals` (`country`) VALUES ("Ecuador");
INSERT INTO `countries_capitals` (`country`) VALUES ("Egypt");
INSERT INTO `countries_capitals` (`country`) VALUES ("El Salvador");
INSERT INTO `countries_capitals` (`country`) VALUES ("Equatorial Guinea");
INSERT INTO `countries_capitals` (`country`) VALUES ("Eritrea");
INSERT INTO `countries_capitals` (`country`) VALUES ("Estonia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Ethiopia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Fiji");
INSERT INTO `countries_capitals` (`country`) VALUES ("Finland");
INSERT INTO `countries_capitals` (`country`) VALUES ("France");
INSERT INTO `countries_capitals` (`country`) VALUES ("Gabon");
INSERT INTO `countries_capitals` (`country`) VALUES ("The Gambia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Georgia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Germany");
INSERT INTO `countries_capitals` (`country`) VALUES ("Ghana");
INSERT INTO `countries_capitals` (`country`) VALUES ("Greece");
INSERT INTO `countries_capitals` (`country`) VALUES ("Grenada");
INSERT INTO `countries_capitals` (`country`) VALUES ("Guatemala");
INSERT INTO `countries_capitals` (`country`) VALUES ("Guinea");
INSERT INTO `countries_capitals` (`country`) VALUES ("Guinea-Bissau");
INSERT INTO `countries_capitals` (`country`) VALUES ("Guyana");
INSERT INTO `countries_capitals` (`country`) VALUES ("Haiti");
INSERT INTO `countries_capitals` (`country`) VALUES ("Honduras");
INSERT INTO `countries_capitals` (`country`) VALUES ("Hungary");
INSERT INTO `countries_capitals` (`country`) VALUES ("Iceland");
INSERT INTO `countries_capitals` (`country`) VALUES ("India");
INSERT INTO `countries_capitals` (`country`) VALUES ("Indonesia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Iran");
INSERT INTO `countries_capitals` (`country`) VALUES ("Iraq");
INSERT INTO `countries_capitals` (`country`) VALUES ("Ireland");
INSERT INTO `countries_capitals` (`country`) VALUES ("Israel");
INSERT INTO `countries_capitals` (`country`) VALUES ("Italy");
INSERT INTO `countries_capitals` (`country`) VALUES ("Jamaica");
INSERT INTO `countries_capitals` (`country`) VALUES ("Japan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Jordan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kazakhstan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kenya");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kiribati");
INSERT INTO `countries_capitals` (`country`) VALUES ("Korea, North");
INSERT INTO `countries_capitals` (`country`) VALUES ("Korea, South");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kosovo");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kuwait");
INSERT INTO `countries_capitals` (`country`) VALUES ("Kyrgyzstan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Laos");
INSERT INTO `countries_capitals` (`country`) VALUES ("Latvia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Lebanon");
INSERT INTO `countries_capitals` (`country`) VALUES ("Lesotho");
INSERT INTO `countries_capitals` (`country`) VALUES ("Liberia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Libya");
INSERT INTO `countries_capitals` (`country`) VALUES ("Liechtenstein");
INSERT INTO `countries_capitals` (`country`) VALUES ("Lithuania");
INSERT INTO `countries_capitals` (`country`) VALUES ("Luxembourg");
INSERT INTO `countries_capitals` (`country`) VALUES ("Macedonia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Madagascar");
INSERT INTO `countries_capitals` (`country`) VALUES ("Malawi");
INSERT INTO `countries_capitals` (`country`) VALUES ("Malaysia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Maldives");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mali");
INSERT INTO `countries_capitals` (`country`) VALUES ("Malta");
INSERT INTO `countries_capitals` (`country`) VALUES ("Marshall Islands");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mauritania");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mauritius");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mexico");
INSERT INTO `countries_capitals` (`country`) VALUES ("Micronesia, Federated States of");
INSERT INTO `countries_capitals` (`country`) VALUES ("Moldova");
INSERT INTO `countries_capitals` (`country`) VALUES ("Monaco");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mongolia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Montenegro");
INSERT INTO `countries_capitals` (`country`) VALUES ("Morocco");
INSERT INTO `countries_capitals` (`country`) VALUES ("Mozambique");
INSERT INTO `countries_capitals` (`country`) VALUES ("Myanmar (Burma)");
INSERT INTO `countries_capitals` (`country`) VALUES ("Namibia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Nauru");
INSERT INTO `countries_capitals` (`country`) VALUES ("Nepal");
INSERT INTO `countries_capitals` (`country`) VALUES ("Netherlands");
INSERT INTO `countries_capitals` (`country`) VALUES ("New Zealand");
INSERT INTO `countries_capitals` (`country`) VALUES ("Nicaragua");
INSERT INTO `countries_capitals` (`country`) VALUES ("Niger");
INSERT INTO `countries_capitals` (`country`) VALUES ("Nigeria");
INSERT INTO `countries_capitals` (`country`) VALUES ("Norway");
INSERT INTO `countries_capitals` (`country`) VALUES ("Oman");
INSERT INTO `countries_capitals` (`country`) VALUES ("Pakistan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Palau");
INSERT INTO `countries_capitals` (`country`) VALUES ("Panama");
INSERT INTO `countries_capitals` (`country`) VALUES ("Papua New Guinea");
INSERT INTO `countries_capitals` (`country`) VALUES ("Paraguay");
INSERT INTO `countries_capitals` (`country`) VALUES ("Peru");
INSERT INTO `countries_capitals` (`country`) VALUES ("Philippines");
INSERT INTO `countries_capitals` (`country`) VALUES ("Poland");
INSERT INTO `countries_capitals` (`country`) VALUES ("Portugal");
INSERT INTO `countries_capitals` (`country`) VALUES ("Qatar");
INSERT INTO `countries_capitals` (`country`) VALUES ("Romania");
INSERT INTO `countries_capitals` (`country`) VALUES ("Russia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Rwanda");
INSERT INTO `countries_capitals` (`country`) VALUES ("Saint Kitts and Nevis");
INSERT INTO `countries_capitals` (`country`) VALUES ("Saint Lucia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Saint Vincent and the Grenadines");
INSERT INTO `countries_capitals` (`country`) VALUES ("Samoa");
INSERT INTO `countries_capitals` (`country`) VALUES ("San Marino");
INSERT INTO `countries_capitals` (`country`) VALUES ("Sao Tome and Principe");
INSERT INTO `countries_capitals` (`country`) VALUES ("Saudi Arabia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Senegal");
INSERT INTO `countries_capitals` (`country`) VALUES ("Serbia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Seychelles");
INSERT INTO `countries_capitals` (`country`) VALUES ("Sierra Leone");
INSERT INTO `countries_capitals` (`country`) VALUES ("Singapore");
INSERT INTO `countries_capitals` (`country`) VALUES ("Slovakia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Slovenia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Solomon Islands");
INSERT INTO `countries_capitals` (`country`) VALUES ("Somalia");
INSERT INTO `countries_capitals` (`country`) VALUES ("South Africa");
INSERT INTO `countries_capitals` (`country`) VALUES ("South Sudan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Spain");
INSERT INTO `countries_capitals` (`country`) VALUES ("Sri Lanka");
INSERT INTO `countries_capitals` (`country`) VALUES ("Sudan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Suriname");
INSERT INTO `countries_capitals` (`country`) VALUES ("Swaziland");
INSERT INTO `countries_capitals` (`country`) VALUES ("Sweden");
INSERT INTO `countries_capitals` (`country`) VALUES ("Switzerland");
INSERT INTO `countries_capitals` (`country`) VALUES ("Syria");
INSERT INTO `countries_capitals` (`country`) VALUES ("Taiwan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Tajikistan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Tanzania");
INSERT INTO `countries_capitals` (`country`) VALUES ("Thailand");
INSERT INTO `countries_capitals` (`country`) VALUES ("Togo");
INSERT INTO `countries_capitals` (`country`) VALUES ("Tonga");
INSERT INTO `countries_capitals` (`country`) VALUES ("Trinidad and Tobago");
INSERT INTO `countries_capitals` (`country`) VALUES ("Tunisia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Turkey");
INSERT INTO `countries_capitals` (`country`) VALUES ("Turkmenistan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Tuvalu");
INSERT INTO `countries_capitals` (`country`) VALUES ("Uganda");
INSERT INTO `countries_capitals` (`country`) VALUES ("Ukraine");
INSERT INTO `countries_capitals` (`country`) VALUES ("United Arab Emirates");
INSERT INTO `countries_capitals` (`country`) VALUES ("United Kingdom");
INSERT INTO `countries_capitals` (`country`) VALUES ("United States of America");
INSERT INTO `countries_capitals` (`country`) VALUES ("Uruguay");
INSERT INTO `countries_capitals` (`country`) VALUES ("Uzbekistan");
INSERT INTO `countries_capitals` (`country`) VALUES ("Vanuatu");
INSERT INTO `countries_capitals` (`country`) VALUES ("Vatican City (Holy See)");
INSERT INTO `countries_capitals` (`country`) VALUES ("Venezuela");
INSERT INTO `countries_capitals` (`country`) VALUES ("Vietnam");
INSERT INTO `countries_capitals` (`country`) VALUES ("Yemen");
INSERT INTO `countries_capitals` (`country`) VALUES ("Zambia");
INSERT INTO `countries_capitals` (`country`) VALUES ("Zimbabwe");