INSERT INTO `countries_capitals` (country, capital) VALUES ("afghanistan", "kabul");
INSERT INTO `countries_capitals` (country, capital) VALUES ("albania", "tirana");
INSERT INTO `countries_capitals` (country, capital) VALUES ("algeria", "algiers");
INSERT INTO `countries_capitals` (country, capital) VALUES ("andorra", "andorra la vella");
INSERT INTO `countries_capitals` (country, capital) VALUES ("angola", "luanda");
INSERT INTO `countries_capitals` (country, capital) VALUES ("antigua and barbuda", "saint john's");
INSERT INTO `countries_capitals` (country, capital) VALUES ("argentina", "buenos aires");
INSERT INTO `countries_capitals` (country, capital) VALUES ("armenia", "yerevan");
INSERT INTO `countries_capitals` (country, capital) VALUES ("australia", "canberra");
INSERT INTO `countries_capitals` (country, capital) VALUES ("austria", "vienna");
INSERT INTO `countries_capitals` (country, capital) VALUES ("azerbaijan", "baku");
INSERT INTO `countries_capitals` (country, capital) VALUES ("the bahamas", "nassau");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bahrain", "manama");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bangladesh", "dhaka");
INSERT INTO `countries_capitals` (country, capital) VALUES ("barbados", "bridgetown");
INSERT INTO `countries_capitals` (country, capital) VALUES ("belarus", "minsk");
INSERT INTO `countries_capitals` (country, capital) VALUES ("belgium", "brussels");
INSERT INTO `countries_capitals` (country, capital) VALUES ("belize", "belmopan");
INSERT INTO `countries_capitals` (country, capital) VALUES ("benin", "porto-novo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bhutan", "thimphu");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bolivia", "la paz (administrative); sucre (judicial)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bosnia and herzegovina", "sarajevo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("botswana", "gaborone");
INSERT INTO `countries_capitals` (country, capital) VALUES ("brazil", "brasilia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("brunei", "bandar seri begawan");
INSERT INTO `countries_capitals` (country, capital) VALUES ("bulgaria", "sofia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("burkina faso", "ouagadougou");
INSERT INTO `countries_capitals` (country, capital) VALUES ("burundi", "gitega (changed from bujumbura in december 2018)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cambodia", "phnom penh");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cameroon", "yaounde");
INSERT INTO `countries_capitals` (country, capital) VALUES ("canada", "ottawa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cape verde", "praia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("central african republic", "bangui");
INSERT INTO `countries_capitals` (country, capital) VALUES ("chad", "n'djamena");
INSERT INTO `countries_capitals` (country, capital) VALUES ("chile", "santiago");
INSERT INTO `countries_capitals` (country, capital) VALUES ("china", "beijing");
INSERT INTO `countries_capitals` (country, capital) VALUES ("colombia", "bogota");
INSERT INTO `countries_capitals` (country, capital) VALUES ("comoros", "moroni");
INSERT INTO `countries_capitals` (country, capital) VALUES ("congo, republic of the", "brazzaville");
INSERT INTO `countries_capitals` (country, capital) VALUES ("congo, democratic republic of the", "kinshasa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("costa rica", "san jose");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cote d'ivoire", "yamoussoukro (official); abidjan (de facto)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("croatia", "zagreb");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cuba", "havana");
INSERT INTO `countries_capitals` (country, capital) VALUES ("cyprus", "nicosia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("czech republic", "prague");
INSERT INTO `countries_capitals` (country, capital) VALUES ("denmark", "copenhagen");
INSERT INTO `countries_capitals` (country, capital) VALUES ("djibouti", "djibouti");
INSERT INTO `countries_capitals` (country, capital) VALUES ("dominica", "roseau");
INSERT INTO `countries_capitals` (country, capital) VALUES ("dominican republic", "santo domingo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("east timor (timor-leste)", "dili");
INSERT INTO `countries_capitals` (country, capital) VALUES ("ecuador", "quito");
INSERT INTO `countries_capitals` (country, capital) VALUES ("egypt", "cairo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("el salvador", "san salvador");
INSERT INTO `countries_capitals` (country, capital) VALUES ("equatorial guinea", "malabo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("eritrea", "asmara");
INSERT INTO `countries_capitals` (country, capital) VALUES ("estonia", "tallinn");
INSERT INTO `countries_capitals` (country, capital) VALUES ("ethiopia", "addis ababa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("fiji", "suva");
INSERT INTO `countries_capitals` (country, capital) VALUES ("finland", "helsinki");
INSERT INTO `countries_capitals` (country, capital) VALUES ("france", "paris");
INSERT INTO `countries_capitals` (country, capital) VALUES ("gabon", "libreville");
INSERT INTO `countries_capitals` (country, capital) VALUES ("the gambia", "banjul");
INSERT INTO `countries_capitals` (country, capital) VALUES ("georgia", "tbilisi");
INSERT INTO `countries_capitals` (country, capital) VALUES ("germany", "berlin");
INSERT INTO `countries_capitals` (country, capital) VALUES ("ghana", "accra");
INSERT INTO `countries_capitals` (country, capital) VALUES ("greece", "athens");
INSERT INTO `countries_capitals` (country, capital) VALUES ("grenada", "saint george's");
INSERT INTO `countries_capitals` (country, capital) VALUES ("guatemala", "guatemala city");
INSERT INTO `countries_capitals` (country, capital) VALUES ("guinea", "conakry");
INSERT INTO `countries_capitals` (country, capital) VALUES ("guinea-bissau", "bissau");
INSERT INTO `countries_capitals` (country, capital) VALUES ("guyana", "georgetown");
INSERT INTO `countries_capitals` (country, capital) VALUES ("haiti", "port-au-prince");
INSERT INTO `countries_capitals` (country, capital) VALUES ("honduras", "tegucigalpa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("hungary", "budapest");
INSERT INTO `countries_capitals` (country, capital) VALUES ("iceland", "reykjavik");
INSERT INTO `countries_capitals` (country, capital) VALUES ("india", "new delhi");
INSERT INTO `countries_capitals` (country, capital) VALUES ("indonesia", "jakarta");
INSERT INTO `countries_capitals` (country, capital) VALUES ("iran", "tehran");
INSERT INTO `countries_capitals` (country, capital) VALUES ("iraq", "baghdad");
INSERT INTO `countries_capitals` (country, capital) VALUES ("ireland", "dublin");
INSERT INTO `countries_capitals` (country, capital) VALUES ("israel", "jerusalem*");
INSERT INTO `countries_capitals` (country, capital) VALUES ("italy", "rome");
INSERT INTO `countries_capitals` (country, capital) VALUES ("jamaica", "kingston");
INSERT INTO `countries_capitals` (country, capital) VALUES ("japan", "tokyo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("jordan", "amman");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kazakhstan", "astana");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kenya", "nairobi");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kiribati", "tarawa atoll");
INSERT INTO `countries_capitals` (country, capital) VALUES ("korea, north", "pyongyang");
INSERT INTO `countries_capitals` (country, capital) VALUES ("korea, south", "seoul");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kosovo", "pristina");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kuwait", "kuwait city");
INSERT INTO `countries_capitals` (country, capital) VALUES ("kyrgyzstan", "bishkek");
INSERT INTO `countries_capitals` (country, capital) VALUES ("laos", "vientiane");
INSERT INTO `countries_capitals` (country, capital) VALUES ("latvia", "riga");
INSERT INTO `countries_capitals` (country, capital) VALUES ("lebanon", "beirut");
INSERT INTO `countries_capitals` (country, capital) VALUES ("lesotho", "maseru");
INSERT INTO `countries_capitals` (country, capital) VALUES ("liberia", "monrovia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("libya", "tripoli");
INSERT INTO `countries_capitals` (country, capital) VALUES ("liechtenstein", "vaduz");
INSERT INTO `countries_capitals` (country, capital) VALUES ("lithuania", "vilnius");
INSERT INTO `countries_capitals` (country, capital) VALUES ("luxembourg", "luxembourg");
INSERT INTO `countries_capitals` (country, capital) VALUES ("macedonia", "skopje");
INSERT INTO `countries_capitals` (country, capital) VALUES ("madagascar", "antananarivo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("malawi", "lilongwe");
INSERT INTO `countries_capitals` (country, capital) VALUES ("malaysia", "kuala lumpur");
INSERT INTO `countries_capitals` (country, capital) VALUES ("maldives", "male");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mali", "bamako");
INSERT INTO `countries_capitals` (country, capital) VALUES ("malta", "valletta");
INSERT INTO `countries_capitals` (country, capital) VALUES ("marshall islands", "majuro");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mauritania", "nouakchott");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mauritius", "port louis");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mexico", "mexico city");
INSERT INTO `countries_capitals` (country, capital) VALUES ("micronesia, federated states of", "palikir");
INSERT INTO `countries_capitals` (country, capital) VALUES ("moldova", "chisinau");
INSERT INTO `countries_capitals` (country, capital) VALUES ("monaco", "monaco");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mongolia", "ulaanbaatar");
INSERT INTO `countries_capitals` (country, capital) VALUES ("montenegro", "podgorica");
INSERT INTO `countries_capitals` (country, capital) VALUES ("morocco", "rabat");
INSERT INTO `countries_capitals` (country, capital) VALUES ("mozambique", "maputo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("Myanmar (Burma)", "Rangoon (Yangon); Naypyidaw or Nay Pyi Taw (administrative)");
INSERT INTO `countries_capitals` (country, capital) values ("namibia", "windhoek");
INSERT INTO `countries_capitals` (country, capital) VALUES ("nauru", "no official capital; government offices in yaren district");
INSERT INTO `countries_capitals` (country, capital) VALUES ("nepal", "kathmandu");
INSERT INTO `countries_capitals` (country, capital) VALUES ("netherlands", "amsterdam; the hague (seat of government)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("new zealand", "wellington");
INSERT INTO `countries_capitals` (country, capital) VALUES ("nicaragua", "managua");
INSERT INTO `countries_capitals` (country, capital) VALUES ("niger", "niamey");
INSERT INTO `countries_capitals` (country, capital) VALUES ("nigeria", "abuja");
INSERT INTO `countries_capitals` (country, capital) VALUES ("norway", "oslo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("oman", "muscat");
INSERT INTO `countries_capitals` (country, capital) VALUES ("pakistan", "islamabad");
INSERT INTO `countries_capitals` (country, capital) VALUES ("palau", "melekeok");
INSERT INTO `countries_capitals` (country, capital) VALUES ("panama", "panama city");
INSERT INTO `countries_capitals` (country, capital) VALUES ("papua new guinea", "port moresby");
INSERT INTO `countries_capitals` (country, capital) VALUES ("paraguay", "asuncion");
INSERT INTO `countries_capitals` (country, capital) VALUES ("peru", "lima");
INSERT INTO `countries_capitals` (country, capital) VALUES ("philippines", "manila");
INSERT INTO `countries_capitals` (country, capital) VALUES ("poland", "warsaw");
INSERT INTO `countries_capitals` (country, capital) VALUES ("portugal", "lisbon");
INSERT INTO `countries_capitals` (country, capital) VALUES ("qatar", "doha");
INSERT INTO `countries_capitals` (country, capital) VALUES ("romania", "bucharest");
INSERT INTO `countries_capitals` (country, capital) VALUES ("russia", "moscow");
INSERT INTO `countries_capitals` (country, capital) VALUES ("rwanda", "kigali");
INSERT INTO `countries_capitals` (country, capital) VALUES ("saint kitts and nevis", "basseterre");
INSERT INTO `countries_capitals` (country, capital) VALUES ("saint lucia", "castries");
INSERT INTO `countries_capitals` (country, capital) VALUES ("saint vincent and the grenadines", "kingstown");
INSERT INTO `countries_capitals` (country, capital) VALUES ("samoa", "apia");
INSERT INTO `countries_capitals` (country, capital) VALUES ("san marino", "san marino");
INSERT INTO `countries_capitals` (country, capital) VALUES ("sao tome and principe", "sao tome");
INSERT INTO `countries_capitals` (country, capital) VALUES ("saudi arabia", "riyadh");
INSERT INTO `countries_capitals` (country, capital) VALUES ("senegal", "dakar");
INSERT INTO `countries_capitals` (country, capital) VALUES ("serbia", "belgrade");
INSERT INTO `countries_capitals` (country, capital) VALUES ("seychelles", "victoria");
INSERT INTO `countries_capitals` (country, capital) VALUES ("sierra leone", "freetown");
INSERT INTO `countries_capitals` (country, capital) VALUES ("singapore", "singapore");
INSERT INTO `countries_capitals` (country, capital) VALUES ("slovakia", "bratislava");
INSERT INTO `countries_capitals` (country, capital) VALUES ("slovenia", "ljubljana");
INSERT INTO `countries_capitals` (country, capital) VALUES ("solomon islands", "honiara");
INSERT INTO `countries_capitals` (country, capital) VALUES ("somalia", "mogadishu");
INSERT INTO `countries_capitals` (country, capital) VALUES ("South Africa", "Pretoria (administrative); Cape Town (legislative); Bloemfontein (judiciary)");
INSERT INTO `countries_capitals` (country, capital) values ("south sudan", "juba");
INSERT INTO `countries_capitals` (country, capital) VALUES ("spain", "madrid");
INSERT INTO `countries_capitals` (country, capital) VALUES ("sri lanka", "colombo; sri jayewardenepura kotte (legislative)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("sudan", "khartoum");
INSERT INTO `countries_capitals` (country, capital) VALUES ("suriname", "paramaribo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("swaziland", "mbabane");
INSERT INTO `countries_capitals` (country, capital) VALUES ("sweden", "stockholm");
INSERT INTO `countries_capitals` (country, capital) VALUES ("switzerland", "bern");
INSERT INTO `countries_capitals` (country, capital) VALUES ("syria", "damascus");
INSERT INTO `countries_capitals` (country, capital) VALUES ("taiwan", "taipei");
INSERT INTO `countries_capitals` (country, capital) VALUES ("tajikistan", "dushanbe");
INSERT INTO `countries_capitals` (country, capital) VALUES ("tanzania", "dar es salaam; dodoma (legislative)");
INSERT INTO `countries_capitals` (country, capital) VALUES ("thailand", "bangkok");
INSERT INTO `countries_capitals` (country, capital) VALUES ("togo", "lome");
INSERT INTO `countries_capitals` (country, capital) VALUES ("tonga", "nuku'alofa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("trinidad and tobago", "port-of-spain");
INSERT INTO `countries_capitals` (country, capital) VALUES ("tunisia", "tunis");
INSERT INTO `countries_capitals` (country, capital) VALUES ("turkey", "ankara");
INSERT INTO `countries_capitals` (country, capital) VALUES ("turkmenistan", "ashgabat");
INSERT INTO `countries_capitals` (country, capital) VALUES ("tuvalu", "vaiaku village, funafuti province");
INSERT INTO `countries_capitals` (country, capital) VALUES ("uganda", "kampala");
INSERT INTO `countries_capitals` (country, capital) VALUES ("ukraine", "kyiv");
INSERT INTO `countries_capitals` (country, capital) VALUES ("united arab emirates", "abu dhabi");
INSERT INTO `countries_capitals` (country, capital) VALUES ("united kingdom", "london");
INSERT INTO `countries_capitals` (country, capital) VALUES ("united states of america", "washington, d.c.");
INSERT INTO `countries_capitals` (country, capital) VALUES ("uruguay", "montevideo");
INSERT INTO `countries_capitals` (country, capital) VALUES ("uzbekistan", "tashkent");
INSERT INTO `countries_capitals` (country, capital) VALUES ("vanuatu", "port-vila");
INSERT INTO `countries_capitals` (country, capital) VALUES ("vatican city (holy see)", "vatican city");
INSERT INTO `countries_capitals` (country, capital) VALUES ("venezuela", "caracas");
INSERT INTO `countries_capitals` (country, capital) VALUES ("vietnam", "hanoi");
INSERT INTO `countries_capitals` (country, capital) VALUES ("yemen", "sanaa");
INSERT INTO `countries_capitals` (country, capital) VALUES ("zambia", "lusaka");
INSERT INTO `countries_capitals` (country, capital) VALUES ("zimbabwe", "harare");